week7/todo/auth_/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hello' , views.hello , name = 'hello'),
    path('home' , views.home , name = 'home'),
    path('login' , views.login , name = 'login'),
    path('registration' , views.registration , name = 'registration'),
]

week7/todo/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.hello),
    path('completed_tasks' , views.completed_tasks , name = "completed_tasks"),
    path('all_tasks' , views.all_tasks),
    path('new_task' , views.new_task , name = "new_task"),
    path('task/<int:task_id>' , views.task_page , name = "task_page"),
]

week7/todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('auth/' , include('auth_.urls')),
]

week7/todo/auth_/models.py
from django.db import models

# Create your models here.

week7/todo/main/models.py
from django.db import models
import datetime


class Owner(models.Model):
    first_name = models.CharField(max_length = 30)
    last_name = models.CharField(max_length = 30)
    email = models.CharField(max_length = 30)

    def __str__(self):
        return self.first_name+' '+self.last_name


class Task(models.Model):
    create_date = models.DateTimeField()
    due_date = models.DateTimeField()
    owner = models.ForeignKey(Owner , on_delete = models.CASCADE)
    done_status = models.BooleanField(default = True)






week7/todo/main/forms.py
from django.forms import ModelForm
from main.models import Task
from django import forms


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('create_date', 'due_date', 'owner', 'done_status' )

week7/todo/auth_/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse , Http404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth

import datetime

# Create your views here.

def hello(request):
    return HttpResponse("hello")

def home(request):
    return render(request, 'home.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            return redirect('home')
        else:
            error = "username or password incorrect"
            return render(request, 'login.html', {'error': error})
    else:
        return render(request, 'login.html')

def registration(request):
    form = UserCreationForm(data = request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        context = {
            'form': form
        }
        return render(request , 'registration.html' , context)





week7/todo/main/views.py
from django.shortcuts import render , redirect
import datetime

# Create your views here.

from django.http import HttpResponse
from .models import Task,Owner
from .forms import TaskForm
from django.http import Http404

def hello(request):
    html = "<html><body>Hello</body></html>"
    return HttpResponse(html)

def all_tasks(request):
    tasks = Task.objects.all()
    todo_list = {
        'tasks': tasks
    }

    return render(request, 'todo_list.html', todo_list)

def completed_tasks(request):
    tasks = Task.objects.filter(done_status = True)

    todo_list = {
        'tasks': tasks
    }

    return render(request, 'completed_todo_list.html', todo_list)


def new_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        print(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            return redirect('./all_tasks')
        else:
            html = "<html><body>Hello</body></html>"
            return HttpResponse(html)
    else:
        form = TaskForm()
        owners = Owner.objects.all()
        context = {
            'form': form,
            'owners': owners
        }
        return render(request, 'new_task.html', context)

def task_page(request , task_id):
    print(request)
    if request.method == 'POST':
        print(1)
        Task.objects.filter(id = task_id).delete()
        return redirect('../all_tasks')
    else:
        try:
            task = Task.objects.get(id = task_id)
        except Task.DoesNotExist:
            raise Http404("There is no such task")
        context = {
            'task': task
        }
        return render(request , 'task/page.html' , context)

week7/todo/auth_/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Welcome!</h1>
    {% if user.is_authenticated %}
        <h1>{{user.username}}</h1>
    {% endif %}
</body>
</html>

week7/todo/auth_/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
     <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="username" class="form-control">
        </div>
        <div class="form-group">
            <input type="password" name="password" class="form-control">
        </div>
        <input type="submit" class="btn btn-primary">
    </form>
</body>
</html>

week7/todo/auth_/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
    <form action="{% url 'registration' %}" method = "POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value = "Register">
    </form>
</body>
</html>

week7/todo/main/templates/completed_todo_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/completed_todo_list-style.css' %}">
    <title>Completed tasks</title>
</head>
<body class = "page">
<header class = "header">
    BFDjango TODO
</header>
    {% block content %}
    <div class = "page__content-wrapper content-wrapper">
    <button type="button" class="add add--style content-wrapper__add">Add task</button>
    <h2>Completed tasks in "List 1"</h2>


    <ul class="content">
        <li class="content__item">
            <div class="col">Task</div>
            <div class="col">Created</div>
            <div class="col">Due on</div>
            <div class="col">Owner</div>
            <div class="col">Mark</div>
        </li>

        {% for task in tasks %}

            <li class="content__item">
                <a href="#">Task {{task.id}}</a>
                <div>{{task.create_date}}</div>
                <div>{{task.due_date}}</div>
                <div>{{task.owner}}</div>
                <button type="button" class="done">
                    {% if task.done_status %}
                        Done
                    {% else %}
                        Not done
                    {% endif %}
                </button>
            </li>

        {% endfor %}


    </ul>
    <button class = "view">View completed tasks</button>
    <button class = "delete">Delete this list</button>
    </div>



{% endblock %}
</body>
</html>

week7/todo/main/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/todo_list-style.css'%}">

    <title>Todo</title>
</head>
<body class = "page">
<header class = "header">
    BFDjango TODO
</header>

{% block content%}
{% endblock %}


week7/todo/main/templates/new_task.html
{% extends 'header.html' %}




{% block content %}
    <form action="{% url 'new_task' %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="id_create_date">Create date: </label>
            <input type="text" name = "create_date" id = "id_create_date">
        </div>
        <div>
            <label for="due_date">Due date: </label>
            <input type="text" name = "due_date" id = "id_due_date">
        </div>
        <div>
            <label for="id_owner">Owner: </label>
            <select name="owner" id="id_owner" required>
                <option value selected>---------</option>
                {% for owner in owners %}
                <option value="{{ owner.id}}">{{owner}}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="done_status">Done status: </label>
            <input type="checkbox" name = "done_status" id = "id_done_status">
        </div>
        <div>
            <input type="submit" value = "create new task">
        </div>
    </form>
{% endblock %}

week7/todo/main/templates/task/page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/task_page-style.css'%}">

    <title>Todo</title>
</head>
<body class = "page">
<header class = "header">
    BFDjango TODO
</header>
<main class = "content">
    Task number: {{task.id}}
    <br>
    Create date: {{ task.create_date }}
    <br>
    Due date: {{ task.due_date }}
    <br>
    Owner: {{ task.owner }}
    <br>
    Done status: {{ task.done_status }}
    <br>
    <form action="{% url 'task_page' task.id %}" method="POST">
        {% csrf_token %}
        <input class = "delete-button" type="submit" value = "Delete this task">
    </form>
</main>

</body>
</html>

week7/todo/main/templates/todo_list.html
{% extends 'header.html' %}

{% block content %}
    <div class = "page__content-wrapper content-wrapper">
    <a type="button" class="add add--style content-wrapper__add" href = "{% url 'new_task' %}">Add task</a>
    <h2>Tasks in "List 1"</h2>


    <ul class="content">
        <li class="content__item">
            <div class="col">Task</div>
            <div class="col">Created</div>
            <div class="col">Due on</div>
            <div class="col">Owner</div>
            <div class="col">Mark</div>
        </li>

        {% for task in tasks %}

            <li class="content__item">
                <a href="{% url 'task_page' task.id %}" >Task {{task.id}}</a>
                <div>{{task.create_date}}</div>
                <div>{{task.due_date}}</div>
                <div>{{task.owner}}</div>
                <button type="button" class="done">
                    {% if task.done_status %}
                        Done
                    {% else %}
                        Not done
                    {% endif %}
                </button>
            </li>

        {% endfor %}


    </ul>
    <a class = "view" href = "{% url 'completed_tasks' %}">View completed tasks</a>
    <button class = "delete">Delete this list</button>
    </div>



{% endblock %}
</body>
</html>